import type { Metadata } from 'next';
import { getTranslations } from 'next-intl/server';
import { LegalPageLayout, LegalSection } from '@/components/layout/legal-page';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: 'meta' });
  return { title: t('nutzungsbedingungen.title') };
}

export default async function NutzungsbedingungenPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isDE = locale === 'de';

  return (
    <LegalPageLayout
      eyebrow={isDE ? 'RECHTLICHES' : 'LEGAL'}
      title={isDE ? 'Nutzungsbedingungen' : 'Terms of Use'}
      backHref={`/${locale}`}
      backLabel={isDE ? 'Zurück zur Startseite' : 'Back to home'}
    >
      {isDE ? (
        <>
          <LegalSection title="1. Geltungsbereich">
            <p>
              Diese Nutzungsbedingungen gelten für die Nutzung des Informationsdienstes
              PermitPro unter der Domain permitpro.de und allen Unterseiten.
            </p>
          </LegalSection>

          <LegalSection title="2. Kein Rechtsrat">
            <p>
              Die von PermitPro generierten Checklisten und bereitgestellten Informationen
              stellen <strong className="text-white">keinen Rechtsrat</strong> dar und ersetzen
              nicht die Beratung durch einen Rechtsanwalt, Architekten oder die zuständige
              Baubehörde.
            </p>
            <p>
              Bei konkreten Bauvorhaben wenden Sie sich bitte an Ihre zuständige untere
              Baubehörde oder einen zugelassenen Fachanwalt für Baurecht.
            </p>
          </LegalSection>

          <LegalSection title="3. Keine Gewähr für Richtigkeit">
            <p>
              PermitPro stellt Informationen nach bestem Wissen und unter Beachtung der
              aktuell geltenden Rechtslage (LBO BW, Stand 18.06.2024) bereit. Für die
              Richtigkeit, Vollständigkeit, Aktualität und Anwendbarkeit auf den konkreten
              Einzelfall kann keine Haftung übernommen werden.
            </p>
            <p>
              Gesetzliche Änderungen, lokale Satzungen oder behördliche Ermessensentscheidungen
              können von den generierten Checklisten abweichen.
            </p>
          </LegalSection>

          <LegalSection title="4. Nutzung auf eigene Verantwortung">
            <p>
              Die Nutzung von PermitPro erfolgt auf eigene Verantwortung des Nutzers. Eine
              Haftung für Schäden, die durch die Nutzung oder Nichtnutzung der bereitgestellten
              Informationen entstehen, ist ausgeschlossen, soweit kein vorsätzliches oder grob
              fahrlässiges Handeln vorliegt.
            </p>
          </LegalSection>

          <LegalSection title="5. Externe Links und Verweise">
            <p>
              PermitPro enthält Links zu externen Websites (z. B. landesrecht-bw.de). Für
              den Inhalt externer Seiten übernehmen wir keine Verantwortung. Die Verlinkung
              dient der Transparenz und Quellenangabe.
            </p>
          </LegalSection>

          <LegalSection title="6. Änderungen des Angebots">
            <p>
              PermitPro behält sich vor, das Angebot jederzeit ohne vorherige Ankündigung zu
              ändern, zu ergänzen oder einzustellen. Ein Anspruch auf Weiterführung des
              Dienstes besteht nicht.
            </p>
          </LegalSection>

          <LegalSection title="7. Anwendbares Recht">
            <p>Es gilt das Recht der Bundesrepublik Deutschland.</p>
          </LegalSection>
        </>
      ) : (
        <>
          <LegalSection title="1. Scope">
            <p>
              These terms of use apply to the use of the PermitPro information service at
              permitpro.de and all sub-pages.
            </p>
          </LegalSection>

          <LegalSection title="2. No legal advice">
            <p>
              The checklists generated by PermitPro and the information provided do{' '}
              <strong className="text-white">not constitute legal advice</strong> and do not
              replace consultation with a lawyer, architect or the responsible building
              authority.
            </p>
            <p>
              For specific construction projects please contact your responsible lower building
              authority or an admitted specialist in construction law.
            </p>
          </LegalSection>

          <LegalSection title="3. No warranty for accuracy">
            <p>
              PermitPro provides information to the best of its knowledge and in accordance
              with the currently applicable legal situation (LBO BW, as of 18.06.2024). No
              liability can be assumed for the accuracy, completeness, topicality or
              applicability to specific individual cases.
            </p>
            <p>
              Legislative changes, local statutes or administrative discretionary decisions
              may deviate from the generated checklists.
            </p>
          </LegalSection>

          <LegalSection title="4. Use at own risk">
            <p>
              Use of PermitPro is at the user&apos;s own risk. Liability for damages arising
              from the use or non-use of the information provided is excluded unless there is
              intentional or grossly negligent conduct.
            </p>
          </LegalSection>

          <LegalSection title="5. External links">
            <p>
              PermitPro contains links to external websites (e.g. landesrecht-bw.de). We
              accept no responsibility for the content of external pages. Links are provided
              for transparency and source referencing.
            </p>
          </LegalSection>

          <LegalSection title="6. Changes to the service">
            <p>
              PermitPro reserves the right to modify, supplement or discontinue the service
              at any time without prior notice. There is no entitlement to continued operation
              of the service.
            </p>
          </LegalSection>

          <LegalSection title="7. Applicable law">
            <p>The law of the Federal Republic of Germany shall apply.</p>
          </LegalSection>
        </>
      )}
    </LegalPageLayout>
  );
}
